#!/bin/bash

#qrsh -g gca50014 -l rt_G.small=1 -l h_rt=12:00:00

#$ -o output/o.$JOB_ID
#$ -l rt_G.small=1
#$ -l h_rt=12:00:00
#$ -j y
#$ -cwd

source /etc/profile.d/modules.sh
module load python/3.6/3.6.12
module load cuda/10.0/10.0.130.1
module load cudnn/7.4/7.4.2
module load nccl/2.4/2.4.8-1

source $HOME/vir/py3/bin/activate

wandb agent --count 50 cecilwang/oss-kfac/gtuuz54r
